# Mostly copied from https://codeberg.org/dnkl/yambar/src/branch/master/examples/configurations/laptop.conf
# and modified

# fonts we'll be reusing here and there
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}
big_font: &big_font Terminess Nerd Font Mono:style=Regular:pixelsize=36


bar:
  location: top
  height: 28
  background: 282a36ff
  margin: 10
  spacing: 8
  font: Terminess Nerd Font Mono:style=Regular:pixelsize=22

  left:
   - dwl:
       number-of-tags: 9
       dwl-info-filename: "/home/g0at/.cache/dwltags"
       name-of-tags: [ 0,1,2,3,4,5,6,7,8 ]
       content:
         list:
           items:
             - map:
                 conditions:
                   # default tag
                   id == 0: {string: {text: "{layout} {title}", max: 45}}
                   selected: {string: {text: " {name} "}}
                   ~empty: {string: {text: "{name} "}}
                   urgent: {string: {text: "󱞪 {name} 󱞦"}}
  right:
    - removables:
        anchors:
          drive: &drive { text: }
          optical: &optical {text: }
        spacing: 5
        content:
          map:
            conditions:
              ~mounted:
                map:
                  on-click: udisksctl mount -b {device}
                  conditions:
                    ~optical: [{string: *drive}, {string: {text: "{label}"}}]
                    optical: [{string: *optical}, {string: {text: "{label}"}}]
              mounted:
                map:
                  on-click: udisksctl unmount -b {device}
                  conditions:
                    ~optical:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    optical:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}
